Fix naming and structure, follow conventions
upleveled/next-13-app-dir-demo-project pull request #5
Opened 2023-01-26 18:41 UTC by karlhorky

Fix some naming, structure and conventions things

@Josehower @ProchaLu @Eprince-hub you should probably all look at all changes in the Files Changed tab and then approve + merge

![Screenshot 2023-01-26 at 19 03 52](https://user-images.githubusercontent.com/1935696/214921819-bc17fa2e-e5ab-4595-8797-e6ae5536320a.png)
![Screenshot 2023-01-26 at 19 05 14](https://user-images.githubusercontent.com/1935696/214921825-ea84535d-bfd9-442b-9169-b64e524efc2a.png)
![Screenshot 2023-01-26 at 19 05 24](https://user-images.githubusercontent.com/1935696/214921828-6d8d88f1-de9c-4cc8-9c3f-252cd3ca386e.png)
![Screenshot 2023-01-26 at 19 05 36](https://user-images.githubusercontent.com/1935696/214921831-5b678817-754f-4759-9453-f200fe6fe868.png)
![Screenshot 2023-01-26 at 19 05 53](https://user-images.githubusercontent.com/1935696/214921832-aab7994e-db29-4929-9560-4014838921b1.png)
![Screenshot 2023-01-26 at 19 07 04](https://user-images.githubusercontent.com/1935696/214921835-8366283a-b4aa-44d2-891e-687c88dd70cf.png)

2023-01-27 08:21 UTC, ProchaLu approved these changes
lgtm 👍

2023-01-29 22:00 UTC, Eprince-hub approved these changes
Looks good ✅

2023-01-30 09:30 UTC, Josehower commented on app/(auth)/register/page.tsx
> +export default async function LoginPage() {
RegisterPage here

2023-01-30 09:32 UTC, Josehower commented on app/animal-management-naive-dont-copy/delete/[animalId]/head.jsx
> +) {
hmm maybe

AnimalManagementNaiveDontCopyAnimalDeleteHeadById ??

this name is not taking into account the [animalId]

2023-01-30 09:33 UTC, Josehower commented on app/animal-management-naive-dont-copy/delete/[animalId]/page.jsx
> +export default async function AnimalManagementNaiveDontCopyAnimalDeletePage(
similar change as here https://github.com/upleveled/next-13-app-dir-demo-project/pull/5/files#r1090370825

2023-01-30 09:34 UTC, Josehower commented on app/animal-management-naive-dont-copy/read/[animalId]/head.jsx
> +export default async function AnimalManagementNaiveDontCopyAnimalReadHead(
this name is not taking into account [animalId]

https://github.com/upleveled/next-13-app-dir-demo-project/pull/5/files#r1090370825

2023-01-30 09:34 UTC, Josehower commented on app/animal-management-naive-dont-copy/read/[animalId]/page.jsx
> +export default async function AnimalManagementNaiveDontCopyAnimalReadPage(
this name is not taking into account [animalId]

[#5 (files)](https://github.com/upleveled/next-13-app-dir-demo-project/pull/5/files#r1090370825)

2023-01-30 09:35 UTC, Josehower commented on app/animal-management-naive-dont-copy/update/[animalId]/head.jsx
> +export default async function AnimalManagementNaiveDontCopyUpdateAnimalHead(
this name is not taking into account [animalId]

[#5 (files)](https://github.com/upleveled/next-13-app-dir-demo-project/pull/5/files#r1090370825)

2023-01-30 09:36 UTC, Josehower commented on app/animal-management-naive-dont-copy/update/[animalId]/page.jsx
> +export default async function AnimalManagementNaiveDontCopyUpdateAnimalPage(
this name is not taking into account [animalId]

[#5 (files)](https://github.com/upleveled/next-13-app-dir-demo-project/pull/5/files#r1090370825)

2023-01-30 09:37 UTC, karlhorky commented on app/(auth)/register/page.tsx
> +export default async function LoginPage() {
[`5500985` (#5)](https://github.com/upleveled/next-13-app-dir-demo-project/pull/5/commits/5500985117b07d77bd63003bf6346f0ea54885a9)

2023-01-30 09:37 UTC, Josehower commented on app/animals/page.tsx
> +import styles from './page.module.scss';
maybe Page.module.scss to follow the capital pattern in other files

2023-01-30 09:37 UTC, karlhorky commented on app/animal-management-naive-dont-copy/delete/[animalId]/head.jsx
> +) {
there's no other delete page yet, so `AnimalManagementNaiveDontCopyAnimalDeleteHead` is unique

2023-01-30 09:38 UTC, karlhorky commented on app/animal-management-naive-dont-copy/delete/[animalId]/page.jsx
> +export default async function AnimalManagementNaiveDontCopyAnimalDeletePage(
there's no other delete page yet, so `AnimalManagementNaiveDontCopyAnimalDeleteHead` is unique

2023-01-30 09:38 UTC, Josehower commented on app/head.tsx
> +export default function HomeHead() {
what about RootHead this is going to apply to any nested page without head

2023-01-30 09:38 UTC, Josehower commented on app/loading.tsx
> +export default function HomeLoading() {
what about RootLoading this is going to apply to any nested page without Loading

2023-01-30 09:39 UTC, Josehower commented on app/page.tsx
> +import styles from './page.module.scss';
capitalization

2023-01-30 09:39 UTC, karlhorky commented on app/animal-management-naive-dont-copy/read/[animalId]/page.jsx
> +export default async function AnimalManagementNaiveDontCopyAnimalReadPage(
- it's `Animal` vs `Animals`, so the id is implied from the name

2023-01-30 09:39 UTC, karlhorky commented on app/animal-management-naive-dont-copy/update/[animalId]/head.jsx
> +export default async function AnimalManagementNaiveDontCopyUpdateAnimalHead(
- it's `Animal` vs `Animals`, so the id is implied from the name

2023-01-30 09:40 UTC, Josehower requested changes
Is almost there i think is a pretty good PR. Just we need to polish some naming

2023-01-30 09:40 UTC, karlhorky commented on app/page.tsx
> +import styles from './page.module.scss';
capitalization already matches the page filename - that's how CSS modules are done most commonly

2023-01-30 09:41 UTC, Josehower commented on app/animal-management-naive-dont-copy/update/[animalId]/head.jsx
> +export default async function AnimalManagementNaiveDontCopyUpdateAnimalHead(
kk

2023-01-30 09:41 UTC, karlhorky commented on app/animals/page.tsx
> +import styles from './page.module.scss';
capitalization already matches the page filename - that's how CSS modules are done most commonly

2023-01-30 09:41 UTC, karlhorky commented on app/animal-management-naive-dont-copy/update/[animalId]/page.jsx
> +export default async function AnimalManagementNaiveDontCopyUpdateAnimalPage(
- it's `Animal` vs `Animals`, so the id is implied from the name

2023-01-30 09:43 UTC, karlhorky commented on app/loading.tsx
> +export default function HomeLoading() {
6c3f0c4379850d9fb3dd3db0f3743d88ee0b9070

2023-01-30 09:43 UTC, karlhorky commented on app/head.tsx
> +export default function HomeHead() {
4e5f7c05b8b4e698c9c36a52e64b821436501435

2023-01-30 09:46 UTC, merged